name: win32_gamepad
description: A package that provides a friendly Dart API for accessing gamepads
  connected to a Windows machine.
version: 1.0.6
homepage: https://win32.pub
repository: https://github.com/dart-windows/win32_gamepad
issue_tracker: https://github.com/dart-windows/win32_gamepad/issues

topics:
  - gamepad
  - win32
  - ffi
  - windows

environment:
  sdk: '^3.1.0'

platforms:
  windows:

dependencies:
  ffi: ^2.1.0
  win32: ^5.0.7

dev_dependencies:
  dartwindows_lints: ^1.0.0
  melos: ^3.1.1
  test: ^1.24.6
