name: win32_gamepad
description: A package that provides a friendly Dart API for accessing gamepads connected to a Windows machine.
version: 1.0.3
repository: https://github.com/timsneath/win32_gamepad
issue_tracker: https://github.com/timsneath/win32_gamepad/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32: ^4.1.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.20.1
