name: inspector
description: A demo project that shows status of gamepads attached to Windows.
publish_to: 'none'

environment:
  sdk: '^3.1.0'

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.6.0
  win32_registry: ^1.1.0
  
  win32_gamepad: 
    path: ../..
  bitsdojo_window: ^0.1.5

flutter:
  uses-material-design: true

dev_dependencies:
  dartwindows_lints: ^1.0.0

dependency_overrides:
  win32: ^5.0.0
  intl: ^0.18.0
