name: inspector
description: A demo project that shows status of gamepads attached to Windows.
publish_to: 'none'

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fluent_ui: ^4.4.2
  win32_registry: ^1.1.0
  
  win32_gamepad: 
    path: ../..
  bitsdojo_window: ^0.1.5

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^2.0.1

dependency_overrides:
  win32: ^4.0.0
  intl: ^0.18.0
