name: inspector
description: A demo project that shows status of gamepads attached to Windows.
publish_to: 'none'

environment:
  sdk: '^3.1.0'

dependencies:
  bitsdojo_window: ^0.1.5
  fluent_ui: ^4.7.4
  flutter:
    sdk: flutter
  win32_gamepad:
    path: ../..
  win32_registry: ^1.1.1

flutter:
  uses-material-design: true

dev_dependencies:
  dartwindows_lints: ^1.0.0

dependency_overrides:
  intl: ^0.18.0
  win32: ^5.0.7
